### ISSUE TITLE
Installation fails at [87%] 

### ISSUE THREAD

**Issue by mKimp** [psu-oss-group/ChatAppFaceID#28]
```
[ 87%] Linking CXX shared library ../../lib/libopencv_tracking.dylib
[ 87%] Built target opencv_tracking
make: *** [all] Error 2
ERR! child process exited with code 2 (for more info, set '--loglevel silly') 
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! opencv-build@0.1.4 install: `node ./install.js`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the opencv-build@0.1.4 install script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /Users/Bone/.npm/_logs/2019-07-18T16_46_31_879Z-debug.log
```

Have anyone got into this problem before? I am using Mac OS Sierra, and it has been working before. After I deleted the folder, clone again from my github, then it failed every time I typed npm install. Can anyone explain why it failed?

Thanks

**Comment by mKimp** [comment]
sorry, wrong place

**Comment by ronniesong0809** [comment]
This is the right place for asking questions. However, sorry I don't have MacOS, and I didn't get into this problem on Ubuntu18.04, I will double-check once again on both Windows and Linux OS.

**Comment by mKimp** [comment]
never mind. I figured it out. I am closing this issue.
