### ISSUE TITLE
Research Facial Recognition Solutions

### ISSUE THREAD

**Issue by ronniesong0809** [psu-oss-group/ChatAppFaceID#6]
Take a look at OpenCV documentation, walk-thought tutorial, and possibly other solutions (packages or libraries)

**Comment by ronniesong0809** [comment]
npm:
[opencv4nodejs](https://www.npmjs.com/package/opencv4nodejs)
[face-recognition](https://www.npmjs.com/package/face-recognition)
[face-detection](https://www.npmjs.com/search?q=face-detection)
[smile-face-detector](https://www.npmjs.com/package/smile-face-detector)

**Comment by mKimp** [comment]
face-recognition is depreciated.
